### Login Admin
POST http://localhost:8000/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin
&password=admin

### Get All Poll
GET http://localhost:8000/api/poll
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTYzMzMxMDA3NSwiZXhwIjoxNjMzMzEzNjc1LCJuYmYiOjE2MzMzMTAwNzUsImp0aSI6Ikx3TGpBR2h2WU1xZFBmWlkiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.1utgcf2tAdtca_adjMQSATfoZ3I2Xp6ZUD6GSEIotLY